document.writeln("				<section class=\'top\'>");
document.writeln("					<div class=\'inner\'>");
document.writeln("						<div class=\'fr\'>");
document.writeln("							<div class=\'block_top_menu\'>");
document.writeln("								<ul>");
document.writeln("									<li class=\'current\'>");
document.writeln("										<div align=\'right\'>");
document.writeln("											<a href=\'#login\' class=\'open_popup\' id=\'cuser\'>登陆</a>");
document.writeln("										</div>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<div align=\'right\'>");
document.writeln("											<a href=\'#\' onClick=\'zhuxiao()\'>注销</a>");
document.writeln("										</div>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'clearboth\'></div>");
document.writeln("					</div>");
document.writeln("				</section>");
document.writeln("				<section class=\'bottom\'>");
document.writeln("					<div class=\'inner\'>");
document.writeln("						<div id=\'logo_top\'>");
document.writeln("							<a href=\'index.html\'><img src=\'images/logo_top.png\'");
document.writeln("								alt=\'BusinessNews\' title=\'竞赛信息网\' /></a>");
document.writeln("						</div>");
document.writeln("						<div class=\'block_today_date\'>");
document.writeln("							<div class=\'num\'>");
document.writeln("								<p id=\'num_top\' />");
document.writeln("							</div>");
document.writeln("							<div class=\'other\'>");
document.writeln("								<p class=\'month_year\'>");
document.writeln("									<span id=\'month_top\'></span>, <span id=\'year_top\'></span>");
document.writeln("								</p>");
document.writeln("								<p id=\'day_top\' class=\'day\' />");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'fr\'>");
document.writeln("							<div class=\'block_languages\'>");
document.writeln("								<div class=\'clearboth\'></div>");
document.writeln("							</div>");
document.writeln("							<div class=\'block_search_top\'>");
document.writeln("								<form action=\'#\'>");
document.writeln("									<div class=\'field\'>");
document.writeln("										<input type=\'text\' class=\'w_def_text\' title=\'输入你想搜索的内容\' />");
document.writeln("									</div>");
document.writeln("									<input type=\'submit\' class=\'button\' value=\'Search\' />");
document.writeln("									<div class=\'clearboth\'></div>");
document.writeln("								</form>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'clearboth\'></div>");
document.writeln("					</div>");
document.writeln("				</section>");