document.writeln("	<div id=\'overlay\'></div>");
document.writeln("	<div id=\'login\' class=\'block_popup\'>");
document.writeln("		<div class=\'popup\'>");
document.writeln("			<a href=\'#\' class=\'close\'>Close</a>");
document.writeln("			<div class=\'content\'>");
document.writeln("				<div class=\'title\'>");
document.writeln("					<p>登陆网站</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'form\'>");
document.writeln("					<form action=\'logincheckaction.action\' name=\'loginform\'>");
document.writeln("						<div class=\'column\'>");
document.writeln("							<p class=\'label\'>用户名</p>");
document.writeln("							<div class=\'field\'>");
document.writeln("								<input type=\'text\' name=\'username\' />");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'column\'>");
document.writeln("							<p class=\'label\'>密码</p>");
document.writeln("							<div class=\'field\'>");
document.writeln("								<input type=\'password\' name=\'password\' />");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'column_2\'>");
document.writeln("							<div class=\'remember\'>");
document.writeln("								<div class=\'checkbox\'>");
document.writeln("									<input type=\'checkbox\' />");
document.writeln("								</div>");
document.writeln("								<div class=\'remember_label\'>");
document.writeln("									<p>记住密码</p>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'column_2\'>");
document.writeln("							<p class=\'forgot_pass\'>");
document.writeln("								<a href=\'#\'>忘记密码?</a>");
document.writeln("							</p>");
document.writeln("						</div>");
document.writeln("						<div class=\'column button\'>");
document.writeln("							<a href=\'#\' class=\'enter\'");
document.writeln("								onclick=\'loginCheck(loginform.username.value,loginform.password.value)\'><span>登陆</span></a>");
document.writeln("						</div>");
document.writeln("						<div class=\'clearboth\'></div>");
document.writeln("					</form>");
document.writeln("");
document.writeln("					<a href=\'registration.html\' target=\'_self\'>");
document.writeln("						<p style=\'padding-top: 25px;\'>注册成为新用户</p>");
document.writeln("					</a>");
document.writeln("					<div style=\'padding-top: 25px;\' id=\'loginresult\'></div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");