document.writeln("	<div class=\'inner\'>");
document.writeln("						<div class=\'block_big_dropdown\' data-menu=\'business\'>");
document.writeln("							<div class=\'content\'>");
document.writeln("								<div class=\'image\'>");
document.writeln("									<a href=\'#\' class=\'pic\'><img");
document.writeln("										src=\'images/pic_big_drop_3.jpg\' alt=\'\' /></a>");
document.writeln("									<p>");
document.writeln("										<a href=\'#\'>这里是火热报名中的竞赛活动。</a>");
document.writeln("									</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'line\'></div>");
document.writeln("								<div class=\'image\'>");
document.writeln("									<a href=\'#\' class=\'pic\'><img");
document.writeln("										src=\'images/pic_big_drop_4.jpg\' alt=\'\' /></a>");
document.writeln("									<p>");
document.writeln("										<a href=\'#\'>这里是快速提升学科素养的通道。</a>");
document.writeln("									</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'line\'></div>");
document.writeln("								<div class=\'popular_posts\'>");
document.writeln("									<div class=\'title\'>");
document.writeln("										<p>商业创业</p>");
document.writeln("									</div>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>2019第八届金程杯全国微课大赛报名中！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>“长沙银行杯”2019年湖南省创新创业大赛和创新挑战赛报名中！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>2019年第十三届iCAN国际创新创业大赛报名中！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>2019年第十三届iCAN国际创新创业大赛报名中！</a></li>");
document.writeln("									</ul>");
document.writeln("								</div>");
document.writeln("								<div class=\'clearboth\'></div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'block_big_dropdown\' data-menu=\'technology\'>");
document.writeln("							<div class=\'content\'>");
document.writeln("								<div class=\'image\'>");
document.writeln("									<a href=\'#\' class=\'pic\'><img");
document.writeln("										src=\'images/pic_big_drop_5.jpg\' alt=\'\' /></a>");
document.writeln("									<p>");
document.writeln("										<a href=\'#\'>这里有正在报名的志愿活动。</a>");
document.writeln("									</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'line\'></div>");
document.writeln("								<div class=\'image\'>");
document.writeln("									<a href=\'#\' class=\'pic\'><img");
document.writeln("										src=\'images/pic_big_drop_6.jpg\' alt=\'\' /></a>");
document.writeln("									<p>");
document.writeln("										<a href=\'#\'>这里有完美闭幕的活动集锦。</a>");
document.writeln("									</p>");
document.writeln("								</div>");
document.writeln("								<div class=\'line\'></div>");
document.writeln("								<div class=\'popular_posts\'>");
document.writeln("									<div class=\'title\'>");
document.writeln("										<p>志愿者招募令</p>");
document.writeln("									</div>");
document.writeln("									<ul>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>金熊猫全球创新创业大赛志愿者招募！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>澳大利亚华人总工会招募线上英文志愿者招募！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>2019第七届#乌镇戏剧节#志愿者招募！</a></li>");
document.writeln("										<li><a href=\'#\'><span>01 July, 2019</span>2019大学生志愿服务西部计划正式招募！</a></li>");
document.writeln("									</ul>");
document.writeln("								</div>");
document.writeln("								<div class=\'clearboth\'></div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				");